provider_config:
  aws:
    ec2_access_key: ""
    ec2_secret_key: ""
    ssh_public_key: /root/.ssh/id_rsa.pub
    ssh_private_key: /root/.ssh/id_rsa
    ssh_user: centos
    instance_type: "t2.large"
    image: "ami-3548444c"
    region: "eu-west-1"
    security_group: "sec-grp-contrail-lab"
    vpc_subnet_id: "subnet-07ab5ce31ed38d490"
    assign_public_ip: yes
    volume_size: 50
    key_pair: "contrail-contrail-lab"
instances:
#  contrail-lab_controller:
#    provider: aws
#    instance_type: t2.xlarge
#    roles:
#      config_database:
#      config:
#      control:
#      analytics_database:
#      analytics:
#      webui:
##      kubemanager:
#      k8s_master:
#  contrail-lab_compute1:
#    provider: aws
#    instance_type: t2.large
#    roles:
#      vrouter:
#      k8s_node:
#  contrail-lab_compute2:
#    provider: aws
#    instance_type: t2.large
#    roles:
#      vrouter:
#      k8s_node:
global_configuration:
  CONTAINER_REGISTRY: "hub.juniper.net/contrail"
  CONTAINER_REGISTRY_USERNAME: JNPR-FieldUser142  
  CONTAINER_REGISTRY_PASSWORD: 
contrail_configuration:
  CONTRAIL_CONTAINER_TAG: 5.0.2-0.360
  UPGRADE_KERNEL: true
